# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        -   id: double-quote-string-fixer
        -   id: check-added-large-files
            args: ['--maxkb=600']
        -   id: check-ast
        -   id: check-json
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: no-commit-to-branch
        -   id: fix-encoding-pragma
        -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4' # 'v1.4.4'  # Use the sha / tag you want to point at
    hooks:
        -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0' # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^proposal/
        additional_dependencies: [pep8-naming]
