@url=
@token=


POST {{url}}/api_proxy
Authorization: {{token}}
content-type: application/json

{
    "question": "How does IFRS S1 help investors with sustainability reporting?",
    "model": "global.anthropic.claude-sonnet-4-5-20250929-v1:0"
}
###